### ISSUE TITLE
Get Error

### ISSUE THREAD

**Issue by CodexJ** [xp4xbox/Python-Backdoor#12]
Hello, Why i get this error when the client connects ?

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Parsa\AppData\Local\Programs\Python\WPy32-3720\python-3.7.2\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Parsa\AppData\Local\Programs\Python\WPy32-3720\python-3.7.2\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Parsa\Desktop\Python-Backdoor-master\server.py", line 522, in work
    socket_accept()
  File "C:\Users\Parsa\Desktop\Python-Backdoor-master\server.py", line 80, in socket_accept
    address += client_info[0], client_info[1], client_info[2],
IndexError: list index out of range

**Comment by xp4xbox** [comment]
Means the client wasn't able to get the computer info. Weird I never got it.

**Comment by CodexJ** [comment]
And also when i use switch "--l" to show the list of connections i get this error, How can i solve it ?

**Comment by CodexJ** [comment]
I fixed it by myself, I changed the port, thanks.

**Comment by xp4xbox** [comment]
ok, must be because the port was in use by something else.
