### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by khodepratik1** [xp4xbox/Python-Backdoor#13]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Shri\\AppData\\Roaming/pyinstaller'

Traceback (most recent call last):
  File "C:\Users\Shri\Downloads\Python-Backdoor-master\Python-Backdoor-master\setup.py", line 115, in <module>
    shutil.rmtree(os.environ["APPDATA"] + "/pyinstaller")
  File "C:\Users\Shri\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Shri\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 374, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\Shri\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 371, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Shri\\AppData\\Roaming/pyinstaller'

**Comment by xp4xbox** [comment]
Try re-installing pyinstaller, it has something to do with the path you installed it to.
