### ISSUE TITLE
I need help :( 

### ISSUE THREAD

**Issue by Yassuomuniesa** [xp4xbox/Python-Backdoor#19]
I dont know how fix this.
```
C:\Users\ELIAS\Downloads\Python-Backdoor-master>python setup.py
1. Use: 192.168.6.245
2. Use a different IP address for server
3. Use a DNS Hostname

Type selection: 1

Enter port number (Press ENTER for default): 3000

Melt file on execution to tmp folder? y/n: y

Add program to startup on launch? y/n: y

Use UPX? y/n (Decreases file size but may not work on fresh computers): n

Path for icon (Press ENTER to skip):
171 INFO: PyInstaller: 3.5
187 INFO: Python: 3.8.0
187 INFO: Platform: Windows-10-10.0.17763-SP0
187 INFO: wrote C:\Users\ELIAS\Downloads\Python-Backdoor-master\client.spec
187 INFO: UPX is not available.
203 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ELIAS\\Downloads\\Python-Backdoor-master',
 'C:\\Users\\ELIAS\\Downloads\\Python-Backdoor-master']
203 INFO: checking Analysis
203 INFO: Building Analysis because Analysis-00.toc is non existent
203 INFO: Initializing module dependency graph...
218 INFO: Initializing module graph hooks...
218 INFO: Analyzing base_library.zip ...
9562 INFO: running Analysis Analysis-00.toc
9577 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\elias\appdata\local\programs\python\python38-32\python.exe
15249 INFO: Caching module hooks...
15265 INFO: Analyzing C:\Users\ELIAS\Downloads\Python-Backdoor-master\client.py
16327 INFO: Processing pre-find module path hook   distutils
17702 INFO: Processing pre-find module path hook   site
17702 INFO: site: retargeting to fake-dir 'c:\\users\\elias\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\fake-modules'
20499 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
26358 INFO: Processing pre-safe import module hook   six.moves
26842 INFO: Processing pre-safe import module hook   win32com
c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\win32com\client\makepy.py:369: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if path is not '' and not os.path.exists(path):
27749 INFO: Loading module hooks...
27749 INFO: Loading module hook "hook-distutils.py"...
27749 INFO: Loading module hook "hook-encodings.py"...
27905 INFO: Loading module hook "hook-lib2to3.py"...
27921 INFO: Loading module hook "hook-numpy.core.py"...
28280 INFO: Loading module hook "hook-numpy.py"...
28280 INFO: Loading module hook "hook-pkg_resources.py"...
29483 INFO: Loading module hook "hook-pydoc.py"...
29483 INFO: Loading module hook "hook-pythoncom.py"...
29983 INFO: Loading module hook "hook-pywintypes.py"...
30483 INFO: Loading module hook "hook-setuptools.py"...
31577 INFO: Loading module hook "hook-sqlite3.py"...
31749 INFO: Loading module hook "hook-sysconfig.py"...
31749 INFO: Loading module hook "hook-win32com.py"...
31905 INFO: Loading module hook "hook-xml.dom.domreg.py"...
31905 INFO: Loading module hook "hook-xml.py"...
32061 INFO: Looking for ctypes DLLs
32092 WARNING: library SbieDll.dll required via ctypes not found
32217 INFO: Analyzing run-time hooks ...
32233 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
32249 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
32249 INFO: Including run-time hook 'pyi_rth_pkgres.py'
32295 INFO: Looking for dynamic libraries
72169 INFO: Looking for eggs
72169 INFO: Using Python library c:\users\elias\appdata\local\programs\python\python38-32\python38.dll
72169 INFO: Found binding redirects:
[]
72200 INFO: Warnings written to C:\Users\ELIAS\Downloads\Python-Backdoor-master\build\client\warn-client.txt
72544 INFO: Graph cross-reference written to C:\Users\ELIAS\Downloads\Python-Backdoor-master\build\client\xref-client.html
72622 INFO: checking PYZ
72622 INFO: Building PYZ because PYZ-00.toc is non existent
72622 INFO: Building PYZ (ZlibArchive) C:\Users\ELIAS\Downloads\Python-Backdoor-master\build\client\PYZ-00.pyz
Traceback (most recent call last):
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ELIAS\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\ELIAS\Downloads\Python-Backdoor-master\client.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\elias\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
```

**Comment by xp4xbox** [comment]
Try using python 3.7

**Comment by Yassuomuniesa** [comment]
Thanks 😃
