### ISSUE TITLE
Keylogger crashes if the victim uses latin characters

### ISSUE THREAD

**Issue by glinskicwb1988** [xp4xbox/Python-Backdoor#22]
OS: Win 10 x64 pro
Commit/Build: 0c53c14

If the victim types latin characters like áéãçéá (all latin languages uses this), etc... the server crashes when dumping:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 535, in work
    main_menu()
  File "server.py", line 110, in main_menu
    send_commands()
  File "server.py", line 507, in send_commands
    keylogger("dump")
  File "server.py", line 413, in keylogger
    strLogs = decode_utf8(recvall(int(intBuffer)))  # get all data
  File "server.py", line 27, in <lambda>
    decode_utf8 = lambda data: data.decode("utf-8")
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 85: unexpected end of **data****

I think adding the correct decoder would solve the problem ?

**Comment by Ridley-nelson17** [comment]
Not that I know much about keyboard characters, but would converting it to it’s Unicode character work?

**Comment by xp4xbox** [comment]
Should work.
