### ISSUE TITLE
cryptography.fernet.InvalidToken Error

### ISSUE THREAD

**Issue by MikcaelX** [xp4xbox/Python-Backdoor#46]
**OS:** Windows 10]

Hi ! I have a problem when i try to do **cd ..** in the terminal

To connect to the shell i do that :

```
>> i 0
You are connected to 127.0.0.1 ....

H Help
M Send message
R Receive file from the user
S Send file to the user
P Take screenshot
A (1) Add to startup
A (2) Remove from startup
V View files
U User Info
E Open remote cmd
I Open remote python interpreter
D Disable task manager
K (start) (stop) (dump) Keylogger
X (1) Lock user
X (2) Restart user
X (3) Shutdown user
B Move connection to background
C Close connection

Type selection: e
```

And after that, when i try to change the dir, i got that : 

```
E:\Developpement\Projet\Python\Backdoor>cd ..
Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\Logiciel\Python 3.8\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Logiciel\Python 3.8\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Développement\Projet\Python\Backdoor\server.py", line 525, in work
    main_menu()
  File "E:\Développement\Projet\Python\Backdoor\server.py", line 117, in main_menu
    send_commands()
  File "E:\Développement\Projet\Python\Backdoor\server.py", line 488, in send_commands
    command_shell()
  File "E:\Développement\Projet\Python\Backdoor\server.py", line 353, in command_shell
    intBuffer = int(recv(intBuff).decode())  # receive buffer size
  File "E:\Développement\Projet\Python\Backdoor\server.py", line 25, in <lambda>
    recv = lambda buffer: objEncryptor.decrypt(conn.recv(buffer))
  File "E:\Logiciel\Python 3.8\lib\site-packages\cryptography\fernet.py", line 76, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "E:\Logiciel\Python 3.8\lib\site-packages\cryptography\fernet.py", line 102, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
```
a solution ? Thanks !

**Comment by xp4xbox** [comment]
im not getting any problems try updating everything.

**Comment by Mikcael-X75** [comment]
I have updated everything and nothings change... 
I'm going to try with a other IP (not 127.0.0.1) to see what's happening...

**Comment by xp4xbox** [comment]
I.tried that it worked for me 

@Y4hL do you think you know what's going on?

**Comment by Y4hL** [comment]
I believe it is because the client and server are out of sync (client is sending buffer size, while server is already trying to decrypt data) and since you can't decrypt something that isn't encrypted it throws an error. It would be important to see if the client is throwing an error aswell and what you might have done before trying the 'cd' command

**Comment by xp4xbox** [comment]
I am getting this error now, i will see how I can fix it
