### ISSUE TITLE
pyinstaller error

### ISSUE THREAD

**Issue by pretech86** [xp4xbox/Python-Backdoor#66]
i get this error when i try compile server file manually 

pyinstaller --onefile --noconsole ./server.py

   
  File "C:\Users\kareem\AppData\Roaming\Python\Python38\site-packages\pytest\__init__.py", line 22, in <module>
    from .test_runner import *    # noqa: F401 F403
  File "C:\Users\kareem\AppData\Roaming\Python\Python38\site-packages\pytest\test_runner.py", line 13, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kareem\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "C:\Users\kareem\PycharmProjects\final_back_door\server.spec", line 7, in <module>
    a = Analysis(['server.py'],
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 420, in assemble
    self.graph.process_post_graph_hooks()
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 367, in process_post_graph_hooks
    module_hook.post_graph()
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 447, in post_graph
    self._load_hook_module()
  File "c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 412, in _load_hook_module
    raise ImportErrorWhenRunningHook(
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_pytest required by hook for module c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pytest.py. Please check whether module __PyInstaller_hooks_0_pytest actually exists and whether the hook is compatible with your version of c:\users\kareem\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pytest.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.

**Comment by pretech86** [comment]
i solved it

**Comment by xp4xbox** [comment]
You are not supposed to compile the server, the server is supposed to run by python.

**Comment by pretech86** [comment]
sorry , i make mistake in typing , i mean client or listener not server

**Comment by xp4xbox** [comment]
I am not sure, I tested it with a fresh python installation, all I can say is try using the latest version of python (3.9)

**Comment by pretech86** [comment]
it's working and i can compile it but when i executed it , it not working

**Comment by xp4xbox** [comment]
Im not sure, try the latest version of python, it works fine for me
