### ISSUE TITLE
screen shot error 

### ISSUE THREAD

**Issue by pretech86** [xp4xbox/Python-Backdoor#69]
**OS:** [e.g. kali]
**Commit/Build:** [e.g. b227928]

when i use p i got the following 

Type selection: p
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "listener.py", line 444, in work
    main_menu()
  File "listener.py", line 108, in main_menu
    send_commands()
  File "listener.py", line 404, in send_commands
    screenshot()
  File "listener.py", line 220, in screenshot
    strScrnSize = recv(intBuff).decode()  # get screenshot size
  File "listener.py", line 16, in <lambda>
    recv = lambda buffer: objEncryptor.decrypt(conn.recv(buffer))
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 74, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 92, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken

**Comment by xp4xbox** [comment]
Duplicate #46

**Comment by pretech86** [comment]
i changed the ip but still the probem occured , i can't take screenshot

**Comment by xp4xbox** [comment]
You can continue the discussion in #46 , it is already a know error.

**Comment by xp4xbox** [comment]
I fixed the error, turns out it was because pillow is needed now for some reason, you can fix it by doing `python -m pip install pillow`

**Comment by pretech86** [comment]
i found i already have it on my kali machine , when i installed it on windows its working fine , so the victim should have it on his os 
i know that it shouldn't according to pyinstaller packaging m but i want to understand

**Comment by pretech86** [comment]
thanks it working now
